#!/usr/bin/env python3
"""
Utility script to visualize training curves from runs/resnet_ft/metrics.csv.
Works in headless WSL environments by saving figures to disk instead of
opening a GUI window.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot ResNet training metrics")
    parser.add_argument(
        "--log-path",
        default="runs/resnet_ft/metrics.csv",
        help="Path to metrics.csv generated by train_resnet_cifar.py",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output image file (default: same folder with '_curve.png')",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=200,
        help="Figure DPI when saving",
    )
    parser.add_argument(
        "--safe",
        action="store_true",
        help="Force Agg backend (useful in headless WSL)",
    )
    return parser.parse_args()


def ensure_backend(args: argparse.Namespace) -> None:
    if args.safe:
        matplotlib.use("Agg")


def main() -> None:
    args = parse_args()
    ensure_backend(args)

    log_path = Path(args.log_path).expanduser().resolve()
    if not log_path.exists():
        raise FileNotFoundError(f"metrics file not found: {log_path}")

    df = pd.read_csv(log_path)
    fig, (ax_acc, ax_loss) = plt.subplots(2, 1, figsize=(8, 8), sharex=True)

    if {"train_acc", "val_acc"}.issubset(df.columns):
        ax_acc.plot(df["epoch"], df["train_acc"], marker="o", label="Train Acc")
        ax_acc.plot(df["epoch"], df["val_acc"], marker="o", label="Val Acc")
        ax_acc.set_ylabel("Accuracy (%)")
        ax_acc.set_title("ResNet CIFAR-10 Accuracy")
        ax_acc.grid(alpha=0.3, linestyle="--")
        ax_acc.legend()

    if {"train_loss", "val_loss"}.issubset(df.columns):
        ax_loss.plot(df["epoch"], df["train_loss"], marker="o", label="Train Loss")
        ax_loss.plot(df["epoch"], df["val_loss"], marker="o", label="Val Loss")
        ax_loss.set_ylabel("CrossEntropy Loss")
        ax_loss.set_xlabel("Epoch")
        ax_loss.set_title("ResNet CIFAR-10 Loss")
        ax_loss.grid(alpha=0.3, linestyle="--")
        ax_loss.legend()

    fig.tight_layout()

    if args.output:
        output_path = Path(args.output).expanduser().resolve()
    else:
        output_path = log_path.with_name(f"{log_path.parent.name}_curve.png")

    fig.savefig(output_path, dpi=args.dpi, bbox_inches="tight")
    print(f"Saved plot to {output_path}")

    if not args.safe:
        try:
            plt.show()
        except Exception as exc:  # pragma: no cover
            print(f"Could not open GUI window ({exc}). Plot saved to {output_path}.")


if __name__ == "__main__":
    main()
